routes/auth.py
from flask import Blueprint, flash, render_template, request, redirect, url_for
from models import *
from db import db
from flask_login import login_required, logout_user, login_user
import hashlib
import secrets

auth_route = Blueprint("auth", __name__)

@auth_route.route("/login", methods=["GET", "POST"])
def login():
    """ Logs in a user OR serves the login page if GET """
    if request.method == "GET": # Check if get then return the login page
        return render_template("login.html")
    
    # Get the username and password from the request
    username = request.form.get("username", None)
    password = request.form.get("hashpasswd", None)
    remember = True if "remember" in request.form else False
    
    # Check to see if username or password are blank. These flash rather than send to error
    if username is None or username == "":
        flash("Username cannot be blank")
        return redirect(url_for("auth.login"))

    if password is None or password == "":
        flash("Password cannot be blank")
        return redirect(url_for("auth.login"))
    
    # Strip Username and password
    username = username.strip()
    password = password.strip()

    user = db.session.execute(db.select(User).where(User.username == username)).scalar()
    if user is None: # Redirect if user is not found
        flash("Username or password may be correct")
        return redirect(url_for("auth.login"))
    
    # Check if password matches 
    hash = hashlib.sha256(password.encode())
    hash.update(user.salt.encode())
    if user.password == hash.hexdigest():
        login_user(user, remember=remember)
        
        # Check if there is a next argument and save the value
        redirect_url = request.args.get("next", None)

        if redirect_url is None:
            return redirect(url_for('dashboard'))
        else:
            return redirect(redirect_url)
    
    flash("Username or password may be correct")
    return redirect(url_for("auth.login"))

@auth_route.route("/signup", methods=["GET", "POST"])
def signup():
    """ Handles the signup process for a new user """
    if request.method == "GET":
        return render_template("signup.html")
    
    # Get the username, password and name from the request
    username = request.form.get("username", None)
    password = request.form.get("hashpasswd", None)
    name = request.form.get("name", username)

    # Check if username or password values are empty. The name will default to username if left blank
    if username is None:
        return render_template("error.html", code=400, message="Username field cannot be left blank"), 400
    
    if password is None:
        return render_template("error.html", code=400, message="Password field cannot be left blank"), 400
    
    # Strip values of trailing spaces
    username = username.strip()
    password = password.strip()
    name = name.strip()

    # Check that the username is not in use
    user = db.session.execute(db.select(User).where(User.username == username)).scalar()
    if user is not None:
        flash("That username already exists")
        return redirect(url_for("auth.signup")), 409
    
    # Generate a salt for the new user
    new_salt = secrets.token_hex(32)
    hash = hashlib.sha256(password.encode())
    hash.update(new_salt.encode())
    password = hash.hexdigest()
    
    # Create the new user and add them to the database
    new_user = User(username=username, name=name, password=password, salt=new_salt)
    db.session.add(new_user)
    db.session.commit()
    
    # Login the user and send them to their homepage
    login_user(new_user)
    return redirect(url_for("dashboard")) # NOTE: Needs to be changed


@auth_route.route("/exists/<string:username>", methods=["GET"])
def get_user_exists(username):
    """ Returns a code to determine if a username exists """
    user = db.session.execute(db.select(User).where(User.username == username)).scalar()

    if user is None:
        return "", 404
    
    # Send the result back
    return "", 200

@auth_route.route("/logout")
@login_required
def logout():
    """ This route when acceced by a logged in user will sign them out of the application """
    logout_user()
    return redirect("/")

routes/lists.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user
from helpers.date_utils import auto_date_parse
from models import *
from db import db
from datetime import datetime as dt
from flask_login import current_user, login_required

list_route = Blueprint("lists", __name__)

@list_route.route("/<int:id>")
@login_required
def get_list(id):
    """ Renders the todo list template for the list given via ID """
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()

    if current_list is None: # check if the list exists and return a 404 error if it does not
        return f"<h1>404</h1><br><h2>List {id} not found</h2>", 404
    
    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403    

    # Logic for order by and show hidden
    select_query = db.select(Todo).where(Todo.list_id == current_list.id)
    match request.args.get("show", None):
        case "true":
            pass
        case _:
            select_query = select_query.where(Todo.complete == False)

    match request.args.get("order", None):
        case "created":
            select_query = select_query.order_by(Todo.created_on.desc())
        case "title":
            select_query = select_query.order_by(Todo.title.asc())
        case "deadline":
            select_query = select_query.order_by(Todo.deadline.asc())

    reminders = db.session.execute(select_query).scalars()

    return render_template("todolist.html", list=current_list, user=user, reminders=reminders)

@list_route.route("/<int:id>/add", methods=["GET"])
@login_required
def get_add_item_form(id):
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None: # check if the list exists and return a 404 error if it does not
        return f"<h1>404</h1><br><h2>List {id} not found</h2>", 404
    
    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403    
    
    return render_template("add-item-form.html", list=current_list)


@list_route.route("/<int:id>/add", methods=["POST"])
@login_required
def add_reminder_to_list(id):
    """ Adds a reminder from the add-item-form to the list """
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None: # check if the list exists and return a 404 error if it does not
        return f"<h1>404</h1><br><h2>List {id} not found</h2>", 404
    
    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403 
    

    form = request.form
    new_reminder = Todo(
        title = form["item-name"],
        description = form["description"],
        deadline = auto_date_parse(form["deadline"]),
        rem_list = current_list
    )
    session.add(new_reminder)
    session.commit()
    return redirect(url_for("lists.get_list", id=id))

@list_route.route("/create_list", methods=["GET"])
@login_required
def creation_page():
    """ Serves the list creation page """
    return render_template("create-list.html", user=current_user.id)

@list_route.route("/create_list/completion", methods=["POST"])
@login_required
def list_created():
    """Creating the list with info user provided"""
    session = db.session
    form = request.form
    
    new_list = List(           
        name= form["list-name"], 
        user=session.execute(db.select(User).where(User.id == current_user.id)).scalar())
    session.add(new_list)
    session.commit()
    return redirect(url_for("lists.get_list", id=new_list.id))


@list_route.route("/rename_list/<int:id>", methods=["GET"])
@login_required
def list_rename_page(id):
    """Sends the HTML Rename page to the user"""
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None:
        return render_template("error.html", message="Cannot edit a list that does not exist", code=404), 404

    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403 

    return render_template("rename-list.html", list=current_list)

@list_route.route("/rename_list/<int:id>/completion", methods=["POST"])
@login_required
def list_rename_done(id):
    """Completing the rename list"""
    session = db.session
    form = request.form
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None: # check that the list exists
        return render_template("error.html", message="Cannot edit a list that does not exist", code=404), 404

    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403 

    current_list.name = form["new-list-name"]
    session.add(current_list)
    session.commit()
    return redirect(url_for("lists.get_list", id=current_list.id))

@list_route.route("/delete_list/<int:id>", methods=["GET"])
@login_required
def list_delete_page(id):
    """ This will get the delete confirmaation page for the user"""
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None: # check that the list exists
        return render_template("error.html", message="Cannot delete a list that does not exist", code=404), 404

    user = current_user
    if user.is_anonymous or current_list.user.id != user.id:
        return render_template("error.html", message="Forbidden", code=403), 403 

    return render_template("delete-list.html", list=current_list)

@list_route.route("/delete_list/<int:id>/completion", methods=["POST"])
@login_required
def list_delete_done(id):
    """ This will get the delete confirmaation page for the user"""
    session = db.session
    current_list = session.execute(db.select(List).where(List.id == id)).scalar()
    
    if current_list is None: # check if the list exists and return a 404 error if it does not
        return render_template("error.html", message=f"List does not exist", code = 404), 404
    
    # Check ownership
    user = current_user
    if current_user.is_anonymous or current_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403

    db.session.delete(current_list)
    db.session.commit()    
    
    return redirect(url_for("dashboard"))

@list_route.route("/<int:id>/delete-complete", methods = ["GET", "POST"])
@login_required
def delete_complete(id):
    """ Deletes all completed reminders in a given list  """
    current_list = db.session.execute(db.select(List).where(List.id == id)).scalar()
    if current_list is None: # check if the list exists and return a 404 error if it does not
        return render_template("error.html", code=404, message="Could not find that list"), 404
    
    # Auth Check
    user = current_user
    if current_user.is_anonymous or current_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403
    
    if request.method == "GET":
        return render_template("post-confirm-dialogue.html", question=f'Delete all completed reminders on "{current_list.name}"', confirm_text="Delete", cancel_text="Cancel", action=url_for("lists.delete_complete", id=id, **request.args))
    
    result = request.form.get("result", None)
    if result == "confirm":
        for todo in current_list.todos:
            if todo.complete:
                db.session.delete(todo)
        db.session.commit()

    return redirect(url_for('lists.get_list', id = current_list.id, **request.args))

routes/reminders.py
from flask import Blueprint, render_template, request, redirect, url_for
from helpers.date_utils import auto_date_parse
from models import *
from db import db
from datetime import datetime as dt
from flask_login import login_required, current_user

reminders_route = Blueprint("reminders", __name__)

@reminders_route.route("/complete/<int:id>", methods=["POST", "PUT"])
@login_required
def mark_reminder_completed_route(id):
    """
    Marks the reminder with the given ID as completed and updating the completion date.\n
    Takes both POST and PUT Requests
    """
    reminder = db.session.execute(db.select(Todo).where(Todo.id == id)).scalar()

    if reminder is None: # test that the reminder exists
        return render_template("error.html", message=f"Reminder could not be found", code = 404), 404
    
    # Check ownership
    if current_user.is_anonymous or reminder.rem_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403

    if reminder.complete: # check reminder not already complete
        return render_template("error.html", message=f"Reminder already completed", code = 409), 409

    
    # Set reminder complete
    reminder.complete = True
    reminder.completed_on = dt.now()

    # Update status in the db
    db.session.add(reminder)
    db.session.commit()

    return redirect(url_for("lists.get_list", id=reminder.rem_list.id, **request.args))

@reminders_route.route("/de-complete/<int:id>", methods=["POST", "PUT"])
@login_required
def mark_reminder_incomplete_route(id):
    """
    Marks an already completed reminder as incomplete again.\n
    This removes the completion date
    """
    reminder = db.session.execute(db.select(Todo).where(Todo.id == id)).scalar()

    if reminder is None: # test that the reminder exists
        return render_template("error.html", message=f"Reminder could not be found", code = 404), 404

    # Check ownership
    if current_user.is_anonymous or reminder.rem_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403
    
    if not reminder.complete: # check reminder already complete
        return render_template("error.html", message=f"Reminder not currently completed", code = 409), 409

    
    reminder.complete = False
    reminder.completed_on = None

    # Update status in the db
    db.session.add(reminder)
    db.session.commit()

    return redirect(url_for("lists.get_list", id=reminder.rem_list.id, **request.args))

@reminders_route.route("/edit/<int:id>", methods=["GET"])
@login_required
def edit_item(id):
    session = db.session
    current_item = session.execute(db.select(Todo).where(Todo.id == id)).scalar()

    if current_item is None: # check if the item exists and return a 404 error if it does not
        return render_template("error.html", message=f"Item does not exist", code = 404), 404
    
    # Check ownership
    if current_user.is_anonymous or current_item.rem_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403
    
    return render_template("edit-item-form.html", reminder=current_item)

@reminders_route.route("/edit/<int:id>/completion", methods=["POST"])
@login_required
def done_edit(id):
    session = db.session
    current_item = session.execute(db.select(Todo).where(Todo.id == id)).scalar()
    
    if current_item is None: # check if the item exists and return a 404 error if it does not
        return render_template("error.html", message=f"Item does not exist", code = 404), 404
    
    # Check ownership
    if current_user.is_anonymous or current_item.rem_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403
    
    form = request.form
    current_item.title = form["item-name"]
    current_item.description = form["description"]
    current_item.deadline = auto_date_parse(form["deadline"])
    session.add(current_item)
    session.commit()
    return redirect(url_for("lists.get_list", id=current_item.rem_list.id, **request.args))

@reminders_route.route("/remove/<int:id>", methods=["GET"])
@login_required
def rm_todo(id):
    session = db.session
    current_item = session.execute(db.select(Todo).where(Todo.id == id)).scalar()
    if current_item is None: # check if the item exists and return a 404 error if it does not
        return render_template("error.html", message=f"Item does not exist", code = 404), 404
    
    # Check ownership
    if current_user.is_anonymous or current_item.rem_list.user.id != current_user.id:
        return render_template("error.html", message="Forbidden", code=403), 403

    list_id = current_item.rem_list.id

    db.session.delete(current_item)
    db.session.commit()    
    
    return redirect(url_for("lists.get_list", id=list_id, **request.args))

templates/add-item-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Item</title>
    <link rel="stylesheet" href="/static/add-item.css">
    <link href="https://fonts.cdnfonts.com/css/pencil-2" rel="stylesheet"> 
    <!-- #Font Choice 1 -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Pangolin&display=swap" rel="stylesheet"> 
    <!-- #Font Choice 2   -->
</head>
<body>
    <h2>Add Item</h2>
    <form id="add-item-form" action="{{ url_for('lists.add_reminder_to_list', id=list.id) }}" method="post">
        <label for="item-name">Item Name:</label><br>
        <input type="text" id="item-name" name="item-name"><br>

        <label for="description">Description:</label><br>
        <textarea id="description" name="description"></textarea><br>

        <label for="deadline">Deadline:</label><br>
        <input type="datetime-local" id="deadline" name="deadline"><br><br>
        
        <button type="submit" onclick="alert('Item added')">Add Item</button>
    </form>
</body>
</html>

templates/create-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/create-list.css">
    <title>Create List</title>
</head>
<body>
    <h1>Create List</h1>
    <form id="list-creation" action="{{ url_for('lists.list_created')}}" method="post" >
      <label for="list-name">List Name:</label>
      <input type="text" id="list-name" name="list-name" required><br><br>
      
      <button type="submit" onclick="alert('List created')">Create List</button></a>
    </form>
</body>
</html>

templates/delete-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete List?</title>
    <link rel="stylesheet" href="/static/delete-list.css">
</head>
<body>
    <h2>Are you sure you would like to delete "{{list.name}}"</h2>
    <form action="{{ url_for('lists.list_delete_done' ,id=list.id)}}" method="post" id="delete-list-form" id="DeleteButton">
        <a href=""><button name="confirm" type="submit" value="confirm">Confirm</button></a>
        <a href="javascript:history.back()"><button name="cancel" type="button" value="cancel" onclick="history.back()">Cancel</button></a>
    </form>
</body>
</html>

templates/edit-item-form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/edit-item-form.css">
    <title>Edit Item</title>
</head>
<body>
    <h2>Edit Item</h2>

    <form id="add-item-form" action="{{ url_for('reminders.done_edit', id=reminder.id) }}" method="post">
        <label for="item-name">Item Name:</label><br>
        <input type="text" id="item-name" name="item-name" value="{{reminder.title}}"><br>

        <label for="description">Description:</label><br>
        <textarea id="description" name="description">{{ reminder.description }}</textarea><br>

        <label for="deadline">Deadline:</label><br>
        <input type="datetime-local" id="deadline" name="deadline" {% if reminder.deadline is ne None %} value="{{ reminder.deadline.strftime('%Y-%m-%dT%H:%M') }}" {% endif %}><br><br>
        
        <button type="submit">Update Item</button>
      </form>
</body>
</html>

templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/error.css">
    <title>Error</title>
</head>
<body>
    <h1>Error x_x</h1>
    <h2>Code : {{ code }} </h2>
    <h2>{{ message }} </h2>
    <a href="javascript:history.back()">Go Back</a></body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Things To Do</title>
    <link rel="stylesheet" href="/static/homepage.css">
</head>
<body>
    <h1>Things To Do</h1>
    <div class="homepage">
        <p>
            Things To Do: A simple way to keep track of your tasks and reminders.
        </p>
        <div class="actions">
            <a href="{{ url_for('auth.login') }}">Login</a>
            <a href="{{ url_for('auth.signup') }}">Sign Up</a>
        </div>
    </div>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log In</title>
    <link rel="stylesheet" href="/static/login.css">
</head>
<body>
    <script src="/static/js/passwordHashing.js"></script>

    <a href="{{ url_for('auth.signup') }}"><button>Sign-Up</button></a>
    <div id="loginForm">
        <h2>Things-To-Do</h2>

        <p style="background-color: red;">{{ ' '.join(get_flashed_messages()) }}</p>
        <label for="username">Username:</label><br>
        <input type="text" id="username" name="username" placeholder="Username" autocomplete="username off"><br>
        <label for="password">Password:</label><br>
        <input type="password" id="password" name="password" placeholder="Password" autocomplete="current-password"><br><br>
        
        <form action="{{url_for('auth.login', next=request.args.get('next', None))}}" method="post" id="main-form">
            <input type="text" id="hiddenusername" name="username" hidden="true">
            <input type="text" id="hashpasswd" name="hashpasswd" hidden="true">
            <input type="checkbox" id="remember" name="remember" value="remember" checked>
            <label for="remember">Remember Me</label><br><br>
        </form>
        <input type="submit" onclick="startLogin()" value="Submit" id="submit">
    </div>
</body>
</html>

templates/post-confirm-dialogue.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm?</title>
</head>
<body>
    <h2>{{ question }}</h2>
    <form method="post" action="{{ action }}">
        <input type="text" value="cancel" name="result" hidden="true">
        <input type="submit" value="{{cancel_text}}">
    </form>
    <form method="post" action="{{ action }}">
        <input type="text" value="confirm" name="result" hidden="true">
        <input type="submit" value="{{confirm_text}}">
    </form>

</body>
</html>

templates/rename-list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rename List</title>
</head>
<body>
    <h1>Rename List</h1>
    <form id="rename-form" action="{{ url_for('lists.list_rename_done', id=list.id)}}" method="post">
        <label for="list-name">Current List Name: {{list.name}}</label>
        <br>
        <label for="new-list-name">New List Name:</label>
        <input type="text" id="new-list-name" name="new-list-name">
        <br>
        <button type="submit">Rename List</button>
    </form>
</body>
</html>

templates/todolist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="/static/todolist.css">

    <link href="https://fonts.cdnfonts.com/css/pencil-2" rel="stylesheet"> 
      <!-- #Font Choice 1           -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Pangolin&display=swap" rel="stylesheet"> 
    <!-- #Font Choice 2 -->
    <title> {{list.name}} </title>
    <style>
        @import url('https://fonts.cdnfonts.com/css/pencil-2'); /* Font 1 import */
        table, td{
            border: 1px solid black ;
        }
    </style>

</head>

<body>

    <div id="sidenavbar">
        <a href="{{ url_for('dashboard')}}" style="float: left;">🏠</a><h2 id="user-list"> User Lists </h2>
        <a href="{{ url_for('lists.creation_page')}}"><button class="create-list" type="button"> Create List </button></a>
                <menu>
                    {% for u_list in user.lists %}
                    <li class="listbutton" style="float: left;"><a href="{{ url_for('lists.get_list', id=u_list.id) }}">{{ u_list.name }}</a>
                        <span style="float: right;"><a href="{{ url_for('lists.list_rename_page', id=list.id) }}">🖊️</a><a href="{{ url_for('lists.list_delete_page', id=list.id)}}">🗑️</a></span></li>
                    {% endfor %}
                </menu>
    </div>
    <div id="list-container">
        <div id="currentList">
            <h2 class="app-name"> Things-To-Do </h2>
                <a href="{{ url_for('auth.logout')}}"><button class="sign-out" type="button"> Sign Out </button></a>

                <h2> {{list.name}} </h2>
             <div class="table-wrapper"> <!--made to ensure table and add item stay aligned with same margins -->
                    <a href="{{ url_for('lists.add_reminder_to_list', id=list.id) }}"> <button class="add-item" type="button"> Add Item </button></a>
                    <table class="lined thick">
                        <tr>
                                <th>Item: </th>
                                <th>Description: </th>
                                <th>Deadline: </th>
                                <th>Due in: </th>
                                <th>Actions:</th>   
                        </tr>

                        <div class="dropdown">
                            <button onclick="dropdownfunction()" class="dropbutton">Sort By</button>
                            <div id="dropdownbuttons" class="dropdown-content">
                                <button style="margin-left: 0px; margin-right:0px;" onclick="updateURL('order', 'deadline')">Urgency</button>
                                <button style="margin-left: 0px; margin-right:0px;" onclick="updateURL('order', 'title')">Title</button>
                                <button style="margin-left: 0px; margin-right:0px;" onclick="updateURL('order', 'created')">Date Created</button>
                            </div>
                        </div>

                        {%for item in reminders%} 
                            <tr class="{{item.colour_helper()}}">
                                <td id="box1">{% if item.complete %}<s>{{item.title}}</s>{% else %}{{item.title}}{% endif %}</td>
                                <td id="box2">{% if item.complete %}<s>{{item.description}}</s>{% else %}{{item.description}}{% endif %}</td>
                                <td id="box3">{% if item.deadline is ne none %} {{item.deadline.strftime("%d-%m-%Y %H:%M")}} {% else %} No Deadline {% endif %}</td>
                                <td id="box4"> {{item.due()}}</td>
                                <td id="box5"><form action="{% if not item.complete %}{{ url_for('reminders.mark_reminder_completed_route', id=item.id, **request.args)}}{% else %}{{ url_for('reminders.mark_reminder_incomplete_route', id=item.id, **request.args)}}{% endif %}" method="post">
                                    <input type="submit" value="{% if not item.complete %} Complete {% else %} Undo-Complete {% endif %}">
                                </form>
                                    <a href="{{ url_for('reminders.edit_item', id=item.id, **request.args)}}"><button type="button"> Edit </button></a>
                                    <a href="{{ url_for('reminders.rm_todo', id=item.id, **request.args)}}"><button type="button" onclick="alert('Item Removed')" > Remove </button></a></td>
                            </tr>
                        {%endfor%}
                    </table>
            </div>
                
                            <button id="toggle-completed" onclick="toggleCompleteShow()" type="button"></button>
                        <a href="{{ url_for('lists.delete_complete', id=list.id, **request.args) }}"><button class="delete-completed-item" type="button"> Delete Completed Reminders </button></a> <br>
        </div>
  
    </div>
<script src="/static/js/queryUpdate.js"></script>
<script src="/static/js/dropdown.js"></script>
</body>

</html>

templates/user_dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.name }}'s Dashboard</title>
    <link href="https://fonts.cdnfonts.com/css/pencil-2" rel="stylesheet"> 
      <!-- #Font Choice 1           -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Pangolin&display=swap" rel="stylesheet"> 
    <link rel="stylesheet" href="/static/todolist.css">
</head>

<body>
    <nav>
        <div id="sidenavbar">
            <h2 id="user-list"> User Lists </h2>
            <a href="{{ url_for('lists.creation_page')}}"><button class="create-list" type="button"> Create
                    List </button></a>
            <menu>
                {% for u_list in user.lists %}
                <li class="listbutton" style="float: left;"><a href="{{ url_for('lists.get_list', id=u_list.id) }}">{{
                        u_list.name }}</a>
                    <span style="float: right;"><a href="{{ url_for('lists.list_rename_page', id=u_list.id) }}">🖊️</a>
                        <a href="{{ url_for('lists.list_delete_page', id=u_list.id)}}">🗑️</a></span>
                </li>
                {% endfor %}
            </menu>
        </div>
    </nav>

    <a href="{{ url_for('auth.logout')}}"><button class="sign-out" type="button"> Sign Out </button></a>
    
    <div id="currentList">
        <h2>Welcome Back {{user.name}}</h2>
    </div>

</body>

</html>